# Generated by Django 4.1.4 on 2022-12-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=20)),
                ('act_shname', models.CharField(max_length=5)),
                ('description', models.TextField()),
            ],
        ),
    ]
